//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: i64,
    pub user_id: i64,
    pub text: String,
    pub has_binary_data: bool,
    pub binary_data_downloaded: bool,
    pub binary_data_path: Option<String>,
    pub binary_data_type: Option<String>,
    pub date: String,
    pub binary_data_reference_expired: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
