name: "Build project with Nix"

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v23
            
      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build project with Nix
        run: |
          nix build . -L
      
      - name: Run tests with Nix
        run: |
          nix flake check . -L

